import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex justify-evenly py-3 text-white bg-green-600">
          {/* <li>
            <a href="/">Home</a>
          </li>
          <li>
            {" "}
            <a href="/about">About</a>
          </li>
          <li>
            {" "}
            <a href="/contact">Contact</a>
          </li>
          <li>
            <a href="/gallery">Gallery</a>
          </li> */}

          <Link className="link" href="/home">
            Home
          </Link>
          <Link className="link" href="/about">
            About
          </Link>
          <Link className="link" href="/contact">
            Contact
          </Link>
          <Link className="link" href="/gallery">
            Gallery
          </Link>
        </ul>

        {children}
      </body>
    </html>
  );
}
